# Generated by Django 5.1.4 on 2024-12-08 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newer', '0004_alter_inventory_category_alter_inventory_item_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profileimg',
            new_name='profile_img',
        ),
    ]
