# Generated by Django 5.1.4 on 2024-12-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newer', '0006_inventory_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
    ]
